### ISSUE TITLE
 ago-tools / samples / registerItems.py  Add note about required fields

### ISSUE THREAD

**Issue by solofoo** [Esri/ago-tools#35]
RegisterItems.py and corresponding function in admin.py:

I don't know if this is because of the way I am running it, but the registerItems function in the admin script errors out if I don't have all of the optional fields in my csv file, including one field not mentioned, "id".
Once I add all these fields (I don't have to actually populate them), the script runs as expected.  Could you add this information to the readme notes?

**Comment by jfrygeo** [comment]
Yes please update readme for required field "id"
