### ISSUE TITLE
Sample to update sourceURL for registered service ?

### ISSUE THREAD

**Issue by TFimpel** [Esri/ago-tools#40]
I need to update the sourceURL for a lot of registered layers. Is that currently supported by the api?

The sample updateRegisteredUrlForServiceOrApp.py updates the url that is assigned to the layer by ArcGIS at time of registration, not the layer's sourceURL (a ArcGIs Server service). Any help is much appreciated. Thanks!

**Comment by ecaldwell** [comment]
Are the registered layers already added to several web maps? If so, then you'll also need to update the service endpoints in the web maps. [This sample](https://github.com/Esri/ago-tools/blob/master/samples/updateMapServiceUrlsInWebMaps.py) shows how to do that.

**Comment by TFimpel** [comment]
Yes, correct. If the registered layer's ArcGIS Online URL changes, then any webmaps need to be updated and the sample your reference works great for that. What I would like to accommodate though, is to change the service endpoints that the registered feature layer itself point to. The use case for this is an organization migrating all their ArcGIS Server services from http://<my_old_server>/arcgis/rest/...  to https://<my_new_server_new>/arcgis/rest/... . 

I just confirmed with ESRI that going through the ArcGIS Online website it makes a difference whether the ArcGIS Server feature service is secured and you are storing credentials with the registered layer in ArcGIS Online. If credentials are stored, the url can NOT be changed in the item Properties section. If credentials are not stored, it IS possible to change the url. I don't know the reason for this behavior.

**Comment by ecaldwell** [comment]
Can you clarify this: "change the service endpoints that the registered feature layer itself point to."

You're talking about changing the url of a registered map service, right? That's what the sample `updateRegisteredUrlForServiceOrApp.py` does.

**Comment by TFimpel** [comment]
Yes, I'm talking about changing the url of a registered map service. The sample updateRegisteredUrlForServiceOrApp.py does not do that IF (1) the map service is secured at the ArcGIS Server tier, AND (2) the credentials are stored with the ArcGIS Online item. 

Even though it doesn't work the sample script still prints "Successfully updated the url."

I had at first misunderstood what the script does, hence my wording "change the service endpoints that the registered feature layer itself point to.". Forget that, sorry for the confusion. I think this is a limitation of ArcGIS Online that is impossible to overcome with a python script. Perhaps it is by design, I don't know. So I believe this case can be closed unless there is something I'm completely missing. Thanks a lot for your help @ecaldwell .

**Comment by ecaldwell** [comment]
OK, I've got it now. I was missing the part about this all being related to *secured* services. I've never looked closely at how a secured service gets stored. I did some testing and it looks like the credentials are actually stored on the backend. The `url` property effectively becomes a proxy for accessing the secured `sourceUrl` endpoint for the service.

I think the closest you could come to automating the update would be to script out the reregistration of the new service endpoints, then updating the `operationalLayers` in each of your web maps to reflect the new `itemId` and `sourceUrl`.

**Comment by TFimpel** [comment]
Thanks for verifying what I'm seeing. I've come to the same conclusion.
