### ISSUE TITLE
Pull users by Groups

### ISSUE THREAD

**Issue by msokolDOIT** [Esri/ago-tools#44]
Would there be a way to add an enhancement to the get users script or a new script to specify a group and pull the users just from that group?

Thanks!

**Comment by ecaldwell** [comment]
Definitely. I'll add it to the list.

**Comment by ecaldwell** [comment]
Well I've definitely been away from this project for too long. All of the pieces needed to do what you want are already in place. Give this a shot.

```
from agoTools.admin import Admin

myAdmin = Admin(username=<username>, password=<password>)
groupInfo = myAdmin.findGroup(<group title>)
groupUsers = myAdmin.getUsersInGroup(groupInfo['id'])

for user in groupUsers['users']:
  print user
```
