### ISSUE TITLE
Problem using migrateAccount()

### ISSUE THREAD

**Issue by mquetel** [Esri/ago-tools#49]
I'm trying to test the migrateAccount() function prior to moving our Org to enterprise logins. Having a problem getting it to run.  

Given the script:

`from agoTools.admin import Admin`
`agolAdmin = Admin('pdx.admin')`
`agolAdmin.migrateAccount('CSMike_demo_cofp', 'mike.quetel')`

I'm getting the following runtime error:

`C:\Tools>python migrate.py`
`Password:`
`Copying all items from CSMike_demo_cofp to mike.quetel...`
`Traceback (most recent call last):`
`  File "migrate.py", line 3, in <module>`
`    agolAdmin.migrateAccount('CSMike_demo_cofp', 'mike.quetel')`
`  File "C:\Python27\ArcGIS10.4\lib\site-packages\agoTools\admin.py", line 353, in migrateAccount`
`    self.reassignAllUser1ItemsToUser2(self, userFrom, userTo)`
`TypeError: reassignAllUser1ItemsToUser2() takes exactly 3 arguments (4 given)`
`C:\Tools>`

Would appreciate any assistance in the correct usage as it must be something simple I'm missing.  Thanks in advance!

**Comment by ecaldwell** [comment]
I'll have to dig into this. This was reported back in #42 and it seems there may be other places this pops up.

 In the meantime, you can try the [standalone version of this script](https://github.com/ecaldwell/portal-admin-examples/blob/master/migrateAccount.py) or check out [ArcREST](https://github.com/Esri/ArcREST) which is much more robust.

**Comment by ecaldwell** [comment]
Should be all fixed now @mquetel. Let me know if you have any other issues with it.
